# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x]
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - run: npm ci
#     - run: npm test
#     - run: npm run build --if-present

name: Node CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm ci
    - run: npm test
    - run: npm run build
